spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com
            client-secret: abcdefghijklmnopqrstuvwxyz
            scope:
              - email
              - profile
